# Generated by Django 3.1.3 on 2021-08-19 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0004_auto_20210815_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='foto',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
